# Config for OFProtectedArea
# Command info:
# There is 3 commands: add, remove, info and tp
# /protectarea add <AreaName> <X> <Z> <Range> adds new area. The are will block certain mobs
# /protectarea remove <AreaName> removes the area.
# /protectarea info <AreaName> gives information about area.
# /protectarea tp <AreaName> teleport sender to area's center.

messages:
  areaNameIsNotAvailable: "The area name is already available!"
  notEnoughPermission: "Only OP players can be use that command!"
  areaIsNotAvailable: "The area is not available!"
  areaRemoved: "The area is removed!"
  areaAdded: "New area added!"
  areaPosIncorrect: "Pos1 and Pos2 is not set yet! Please use wooden axe like world edit!"
  pos1set: "Pos1 is set, when you right click to another block Pos2 will be set!"
  pos2set: "Pos2 set, now you can use /protectedarea add <areaname>"


# Please use "" and don't forget put ,
unwantedMobs: [
  "Pig",
  "Bee"
]