# Config for OFProtectedArea
# Command info:
# There is 3 commands: add, remove, info and tp
# /protectarea add <AreaName> <X> <Z> <Range> adds new area. The are will block certain mobs
# /protectarea remove <AreaName> removes the area.
# /protectarea info <AreaName> gives information about area.
# /protectarea tp <AreaName> teleport sender to area's center.

messages:
  areaNameIsNotAvailable: "&b[OFProtectedArea] &6>>> &4The area name is already in usage!"
  notEnoughPermission: "&b[OFProtectedArea] &6>>> &4Only OP players can be use that command!"
  areaIsNotAvailable: "&b[OFProtectedArea] &6>>> &4The area is not available!"
  areaRemoved: "&b[OFProtectedArea] &6>>> &2The area is removed!"
  areaAdded: "&b[OFProtectedArea] &6>>> &2New area added!"
  areaPosIncorrect: "&b[OFProtectedArea] &6>>> &4Pos1 and Pos2 is not set yet! Please use wooden axe (worldedit)."

# Please use "" and don't forget put ,
unwantedMobs: [
  "Pig",
  "Bee"
]